[package]
name        = "hologram-monitoring-server"
version     = "1.2.0"
description = "hologram: VPN server for monitoring"

requires = [
  'hologram-monitoring-agents',
  'wireguard-dkms',
  'wireguard-tools',
]

[[directory]]
path = "/etc/wireguard"
mode = "0700" # contains private keys

# open port when using hologram-ferm
[[file]]
path    = "/etc/ferm.d/incoming-wireguard"
content = "proto udp dport {{.Vars.wg.port}} ACCEPT;"
[[symlink]]
path   = "/usr/share/holo/files/20-monitoring-server/etc/ferm.d/incoming-wireguard.holoscript"
target = "/usr/bin/replicator"

################################################################################
# private network for metric collection

[[file]]
path = "/etc/wireguard/wg-monitoring.conf"
content = '''
  [Interface]
  Address = {{.Vars.prometheus.slash24}}.{{.Vars.host.id}}/32
  PrivateKey = {{.Vars.wg.private_key}}
  ListenPort = {{.Vars.wg.port}}
  PostUp = sysctl net.ipv4.conf.wg-monitoring.forwarding=1

  {{range $hostname, $cfg := .Vars.wg.peers}}
  {{- if ne $hostname $.Vars.host.name}}
  [Peer]
  PublicKey = {{$cfg.public_key}}
  PresharedKey = {{$.Vars.wg.preshared_key}}
  AllowedIPs = {{$.Vars.prometheus.slash24}}.{{$cfg.machine_id}}/32

  {{- end}}
  {{- end}}
'''
[[symlink]]
path   = "/usr/share/holo/files/20-monitoring-server/etc/wireguard/wg-monitoring.conf.holoscript"
target = "/usr/bin/replicator"

[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/wg-quick@wg-monitoring.service"
target = "/usr/lib/systemd/system/wg-quick@.service"

# enable peers to talk to each other over the monitoring network
[[file]]
path    = "/etc/ferm.d/forwarding-wg-monitoring"
content = '''
  interface wg-monitoring outerface wg-monitoring ACCEPT;
'''
