[package]
name        = "hologram-base-gui-minimal"
version     = "1.2.2"
description = "hologram: base GUI installation (variant for space-constrained systems)"

requires = [
    "hologram-base-accessible",
    "xorg-server",
    # assorted GUI apps
    "group:xorg-apps",
    "firefox",
    "graphviz",
    "gnuplot",
    "gvim", # vim with X11 clipboard support
    "imagemagick",
    "inkscape",
    "mupdf",
    "paprefs",
    "pavucontrol",
    "qgit",
    "quickstart",
    "screen-message",
    "sxiv",
    "xsel",
    # helper packages
    "aspell-de",  # to silence complaints in gitk about missing spell check dict
    "human-icon-theme",
    # font packages
    "adobe-source-code-pro-fonts",
    "adobe-source-sans-pro-fonts",
    "adobe-source-serif-pro-fonts",
    "gnu-free-fonts",
    "ttf-bitstream-vera",
    "ttf-dejavu",
    "ttf-droid",
    "ttf-liberation",
]

# set keymap for XKB

[[file]]
path = "/etc/X11/xorg.conf.d/keyboard.conf"
content = '''
    Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "en"
        Option "XkbVariant" "altgr-intl"
        Option "XkbOptions" "caps:escape"
    EndSection
'''

[[file]]
path = "/etc/profile.d/xkb.sh"
content = '''
    export XKB_DEFAULT_LAYOUT=us
    export XKB_DEFAULT_VARIANT=altgr-intl
    export XKB_DEFAULT_OPTIONS=caps:escape
'''

[[file]]
path = "/etc/profile.d/no-hidpi-please.sh"
content = '''
    unset QT_AUTO_SCREEN_SCALE_FACTOR
    export GDK_SCALE=1
'''
