[package]
name        = "hologram-damogran-dyndns"
version     = "3.0.1"
description = "hologram: DynDNS setup for Damogran (using Gandi API)"
requires    = [
    "secrets", # this uses /usr/bin/replicator
    "gandi-automatic-dns",
]
replaces    = [ "gandi-dyndns" ]

[[file]]
path    = "/usr/lib/update-gandi-dyndns"
mode    = "0700" # contains secrets
content = '''
    #!/bin/sh
    exec \
      sudo -u nobody -g nobody \
      gad -5 -l 600 -i {{.Vars.interfaces.wan}} -a "{{.Vars.dyndns.api_key}}" -d "{{.Vars.dyndns.domain}}" -r "damogran" -v
'''
[[symlink]]
path   = "/usr/share/holo/files/50-damogran-vars/usr/lib/update-gandi-dyndns.holoscript"
target = "/usr/bin/replicator"

[[file]]
path    = "/usr/lib/systemd/system/gandi-dyndns.service"
content = """
    [Unit]
    Description=Check and update DNS entries
    After=network-online.target
    Wants=network-online.target

    [Service]
    Type=oneshot
    ExecStart=/usr/lib/update-gandi-dyndns
"""
[[file]]
path    = "/usr/lib/systemd/system/gandi-dyndns.timer"
content = """
    [Unit]
    Description=Check and update DNS entries every five minutes
    After=network-online.target
    Wants=network-online.target

    [Timer]
    OnBootSec=1min
    OnUnitActiveSec=5min

    [Install]
    WantedBy=timers.target
"""

[[symlink]]
path   = "/etc/systemd/system/timers.target.wants/gandi-dyndns.timer"
target = "/usr/lib/systemd/system/gandi-dyndns.timer"
