[package]
name        = "hologram-xyrillian"
version     = "0.1"
description = "hologram: setup and automation for https://xyrillian.de"

requires = [
    "secrets", # this uses /usr/bin/replicator
    "hologram-nginx",
    "hookserve",
]

################################################################################
# dedicated user account for running deployment under

[[group]]
name   = "xyrillian"
system = true

[[user]]
name   = "xyrillian"
group  = "xyrillian"
system = true
home   = "/var/lib/xyrillian"
shell  = "/usr/bin/nologin"

[[directory]]
path = "/var/lib/xyrillian"
mode  = "0700"
owner = "xyrillian"
group = "xyrillian"

################################################################################
# deployment targets for website contents

[[directory]]
path  = "/data/static-web/xyrillian.de"
mode  = "0755"
owner = "xyrillian"
group = "xyrillian"

[[symlink]]
path   = "/data/static-web/www.xyrillian.de"
target = "xyrillian.de"

################################################################################
# redirects for auxiliary domains

[[file]]
path    = "/etc/nginx/sites-enabled/redirects-to-xyrillian.conf"
content = '''
    server {
        server_name garnichtsoeinfach-podcast.de;
        include     /etc/nginx/server-baseline-https.inc;

        ssl_certificate     /etc/letsencrypt/live/garnichtsoeinfach-podcast.de/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/garnichtsoeinfach-podcast.de/privkey.pem;
        ssl_trusted_certificate /etc/letsencrypt/live/garnichtsoeinfach-podcast.de/chain.pem;

        location / {
            return 301 https://xyrillian.de/noises/;
        }
    }

    server {
        server_name www.garnichtsoeinfach-podcast.de;
        include     /etc/nginx/server-baseline-https.inc;

        ssl_certificate     /etc/letsencrypt/live/www.garnichtsoeinfach-podcast.de/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/www.garnichtsoeinfach-podcast.de/privkey.pem;
        ssl_trusted_certificate /etc/letsencrypt/live/www.garnichtsoeinfach-podcast.de/chain.pem;

        location / {
            return 301 https://xyrillian.de/noises/;
        }
    }
'''

################################################################################
# Github webhook that triggers the deployment

[[file]]
path    = "/etc/nginx/sites-enabled/hook-xyrillian.conf"
content = '''
    server {
        server_name hook.xyrillian.de;
        include     /etc/nginx/server-baseline-https.inc;

        add_header  Content-Security-Policy "default-src 'self' 'unsafe-inline'" always; # unsafe-inline for <style> tag to work

        ssl_certificate     /etc/letsencrypt/live/hook.xyrillian.de/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/hook.xyrillian.de/privkey.pem;
        ssl_trusted_certificate /etc/letsencrypt/live/hook.xyrillian.de/chain.pem;

        location / {
            proxy_pass http://localhost:8723;
        }
    }
'''
[[file]]
path = "/usr/lib/xyrillian/hookserve.sh"
mode = "0755"
contentFrom = "src/xyrillian-hookserve.sh"

[[file]]
path    = "/usr/lib/systemd/system/hookserve-xyrillian.service"
content = '''
    [Unit]
    Description=React to Github events pushed to hook.xyrillian.de

    [Service]
    ExecStart=/usr/bin/hookserve --port=8723 --secret={{.Vars.hookserve.secret}} /usr/lib/xyrillian/hookserve.sh

    [Install]
    WantedBy=multi-user.target
'''
[[symlink]]
path   = "/usr/share/holo/files/50-bethselamin-vars/usr/lib/systemd/system/hookserve-xyrillian.service.holoscript"
target = "/usr/bin/replicator"

[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/hookserve-xyrillian.service"
target = "/usr/lib/systemd/system/hookserve-xyrillian.service"

################################################################################
# deployment task

[[file]]
path    = "/usr/lib/xyrillian/update.sh"
mode    = "0755"
content = '''
    #!/bin/bash
    set -euo pipefail
    cd /var/lib/xyrillian
    if [ -d data ]; then
        git -C data pull -q origin master
    else
        git clone https://github.com/majewsky/xyrillian.de data
    fi
    rsync -au --exclude .git/ --delete-delay data/ /data/static-web/xyrillian.de/
'''

[[file]]
path = "/usr/lib/systemd/system/xyrillian-update.service"
content = '''
    [Unit]
    Description=Update xyrillian.de

    [Service]
    Type=oneshot
    ExecStart=/usr/lib/xyrillian/update.sh
    User=xyrillian
    Group=xyrillian
'''
