[package]
name        = "holodeck-work-lxc"
version     = "1.0.1"
description = "holodeck: base configuration for headless LXC containers"

requires = [
  "hologram-base-accessible",
  "hologram-dev-tools-minimal",
  # assorted tools
  "docker",
  "ipython",
  "nload",
  "npm",
  "postgresql",
  "python-pip",
  "python-virtualenv",
  "redis",
  "rfc",
  "sshuttle",
]

[[user]]
name   = "stefan"
groups = ["docker"]

[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/docker.service"
target = "/usr/lib/systemd/system/docker.service"

[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/postgresql.service"
target = "/usr/lib/systemd/system/postgresql.service"
