[package]
name        = "hologram-base-gui-minimal"
version     = "1.1.5"
description = "hologram: base GUI installation (variant for space-constrained systems)"

requires = [
    "hologram-base-accessible",
    "xorg-server",
    # assorted GUI apps
    "group:xorg-apps",
    "firefox",
    "graphviz",
    "gnuplot",
    "gvim", # vim with X11 clipboard support
    "inkscape",
    "mupdf",
    "paprefs",
    "pavucontrol",
    "qgit",
    "quickstart",
    "screen-message",
    "sxiv",
    "xsel",
    # helper packages
    "aspell-de",  # to silence complaints in gitk about missing spell check dict
    "human-icon-theme",
    # font packages
    "adobe-source-code-pro-fonts",
    "adobe-source-sans-pro-fonts",
    "adobe-source-serif-pro-fonts",
    "ttf-bitstream-vera",
    "ttf-dejavu",
    "ttf-droid",
    "ttf-freefont",
    "ttf-liberation",
]

# install a custom X11 keymap addon (see comments in src/xkb/symbols.txt)

[[file]]
path = "/usr/share/X11/xkb/symbols/stefan"
contentFrom = "src/xkb/symbols.txt"

[[file]]
path = "/usr/share/holo/files/00-base/usr/share/X11/xkb/rules/base.holoscript"
mode = "0755"
contentFrom = "src/xkb/rules.holoscript"

[[file]]
path = "/usr/share/holo/files/00-base/usr/share/X11/xkb/rules/base.lst.holoscript"
mode = "0755"
contentFrom = "src/xkb/rules.lst.holoscript"

[[file]]
path = "/usr/share/holo/files/00-base/usr/share/X11/xkb/rules/base.xml.holoscript"
mode = "0755"
contentFrom = "src/xkb/rules.xml.holoscript"

[[file]]
path = "/usr/share/holo/files/00-base/usr/share/X11/xkb/rules/evdev.holoscript"
mode = "0755"
contentFrom = "src/xkb/rules.holoscript"

[[file]]
path = "/usr/share/holo/files/00-base/usr/share/X11/xkb/rules/evdev.lst.holoscript"
mode = "0755"
contentFrom = "src/xkb/rules.lst.holoscript"

[[file]]
path = "/usr/share/holo/files/00-base/usr/share/X11/xkb/rules/evdev.xml.holoscript"
mode = "0755"
contentFrom = "src/xkb/rules.xml.holoscript"

# instruct XKB to use this custom keymap

[[file]]
path = "/etc/X11/xorg.conf.d/keyboard.conf"
content = '''
    Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "de"
        Option "XkbVariant" "nodeadkeys"
        Option "XkbOptions" "caps:escape,stefan:map"
    EndSection
'''

[[file]]
path = "/etc/profile.d/xkb.sh"
content = '''
    export XKB_DEFAULT_LAYOUT=de
    export XKB_DEFAULT_VARIANT=nodeadkeys
    export XKB_DEFAULT_OPTIONS=caps:escape,stefan:map
'''

[[file]]
path = "/etc/profile.d/no-hidpi-please.sh"
content = '''
    export QT_AUTO_SCREEN_SCALE_FACTOR=1
    export GDK_SCALE=1
'''
