[package]
name        = "hologram-virtualbox-guest"
version     = "1.0.2"
description = "Hologram: kernel modules, bootloader, network setup for VirtualBox VMs"

provides  = [ "hologram-vm-guest" ]
conflicts = [ "hologram-vmware-guest" ]

requires = [
    "hologram-uefi-bootloader",
    "linux-headers",
    "virtualbox-guest-utils",
    "xf86-video-fbdev",
    "xf86-video-vesa",
]

[[file]]
path    = "/etc/modules-load.d/virtualbox.conf"
content = '''
    vboxguest
    vboxsf
    vboxvideo
'''

################################################################################
# file sharing with host

[[file]]
path = "/usr/share/holo/files/20-virtualbox/etc/fstab.holoscript"
mode = "0755"
content = '''
    #!/bin/sh
    cat
    echo "VMShare /mnt/vmshare vboxsf rw,uid=1001,gid=100,noauto 0 0"
'''

################################################################################
# network setup

[[file]]
path    = "/etc/systemd/network/dhcp.network"
content = """
    [Match]
    Name=en*

    [Network]
    Description=DHCP to host
    DHCP=yes

    [DHCP]
    UseDomains=true
"""

# use systemd-resolved
[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/systemd-resolved.service"
target = "/usr/lib/systemd/system/systemd-resolved.service"

[[symlink]]
path   = "/usr/share/holo/files/20-virtualbox/etc/resolv.conf"
target = "/run/systemd/resolve/resolv.conf"
