[package]
name        = "holodeck-krikkit"
version     = "20191121.1"
description = "holodeck: services on Krikkit"
requires    = [
    "hologram-kde-desktop",
    "hologram-sway-desktop",
    "hologram-dev-tools",
    "hologram-games",
    "hologram-dtp",
    "hologram-uefi-bootloader-with-luks",
    "hologram-monitoring-client",
    # hardware support
    "intel-ucode",
    "wpa_supplicant",
    "xf86-input-synaptics",
    # power management
    "tlp",
    "x86_energy_perf_policy", # optional dependency for tlp
    # support for Intel GPU
    "xf86-video-intel",
    "libva-intel-driver",
    "vulkan-intel",
    "vulkan-icd-loader",
    "lib32-vulkan-intel",
    "lib32-vulkan-icd-loader",
    # applications
    "kdeconnect",
    "libreoffice-still",
    "mpd",
    "powerdevil",    # skipped in hologram-kde-desktop
    # trial runs
    "wireguard-tools",
    "linux-headers", # for virtualbox-host-dkms
]

[[file]]
path    = "/etc/hostname"
content = "krikkit"

[[file]]
path    = "/etc/profile.d/prettyprompt.sh"
content = """
export PRETTYPROMPT_COMMONUSER=stefan
export PRETTYPROMPT_HOSTCOLOR='0;32'
"""

# enable VirtualBox for my user account
[[user]]
name = "stefan"
groups = ["vboxusers"]

# Xorg: enable palm detection on touchpad
[[file]]
path    = "/etc/X11/xorg.conf.d/52-palm-detection.conf"
content = """
Section "InputClass"
    Identifier "touchpad enable palm detection"
    Driver "synaptics"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    Option "PalmDetect" "on"
    Option "PalmMinWidth" "4"
    Option "PalmMinZ" "1"
    Option "TapButton1" "1"
    Option "TapButton2" "2"
    Option "TapButton3" "3"
EndSection
"""

# network setup: systemd-networkd
[[file]]
path    = "/etc/systemd/network/dhcp.network"
content = """
    [Match]
    Name=wl* en*

    [Network]
    Description=Use DHCP on physical interfaces
    DHCP=yes

    [DHCP]
    UseDomains=true
"""

# network setup: systemd-resolved
[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/systemd-resolved.service"
target = "/usr/lib/systemd/system/systemd-resolved.service"

[[symlink]]
path   = "/usr/share/holo/files/50-krikkit/etc/resolv.conf"
target = "/run/systemd/resolve/resolv.conf"

# network setup: wpa_supplicant
[[file]]
path = "/etc/wpa_supplicant/wpa_supplicant-wlp2s0.conf"
contentFrom = "/dev/null"
[[file]]
path    = "/usr/share/holo/files/50-krikkit/etc/wpa_supplicant/wpa_supplicant-wlp2s0.conf.holoscript"
mode    = "0755"
content = '''
    #!/bin/sh
    cat /home/stefan/.wpa_supplicant.conf
    cat /etc/wpa_supplicant/wpa_supplicant.conf
'''

[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/wpa_supplicant@wlp2s0.service"
target = "/usr/lib/systemd/system/wpa_supplicant@.service"

# /etc/pulse/default.pa: disable corking which would mute MPD while Mumble or Skype are running
[[file]]
path = "/usr/share/holo/files/50-krikkit/etc/pulse/default.pa.holoscript"
mode = "0755"
content = """
#!/bin/sh
sed '/load-module module-role-cork/d'
"""

[[file]]
path = "/etc/systemd/logind.conf.d/no-magic-suspend.conf"
content = """
[Login]
HandlePowerKey=ignore
HandleLidSwitch=ignore
"""

# sway: touchpad configuration
[[file]]
path = "/etc/sway/config.d/touchpad"
content = '''
    input "2:14:ETPS/2_Elantech_Touchpad" {
      accel_profile adaptive
      click_method button_areas
      dwt enabled # disable while typing
      events disabled_on_external_mouse
      middle_emulation enabled
      scroll_method two_finger
      tap enabled
    }
'''

# enable TLP (laptop power-saving daemon)

[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/tlp.service"
target = "/usr/lib/systemd/system/tlp.service"
[[symlink]]
path   = "/etc/systemd/system/sleep.target.wants/tlp-sleep.service"
target = "/usr/lib/systemd/system/tlp-sleep.service"

[[symlink]]
path   = "/etc/systemd/system/NetworkManager.service"
target = "/dev/null"
[[symlink]]
path   = "/etc/systemd/system/systemd-rfkill.service"
target = "/dev/null"
[[symlink]]
path   = "/etc/systemd/system/systemd-rfkill.socket"
target = "/dev/null"
