[package]
name        = "hologram-overlay-network-server"
version     = "0.0.4"
description = "hologram: server for private overlay network"

requires = [
  'linux-headers', # for DKMS
  'wireguard-dkms',
  'wireguard-tools',
]

################################################################################
# WireGuard device

[[file]]
path    = "/usr/lib/systemd/network/wg-overlay.netdev"
mode    = "0640" # this file contains private keys
owner   = "root"
group   = "systemd-network"
content = '''
  {{- $n := .Vars.network.overlay }}
  [NetDev]
  Name = wg-overlay
  Kind = wireguard
  Description = Overlay network between all my machines

  [WireGuard]
  PrivateKey = {{$n.private_key}}
  ListenPort = {{$n.listen_port}}

  {{- range $hostname, $cfg := $n.peers }}
  {{- if ne $hostname $.Vars.host.name}}
  [WireGuardPeer]
  {{- if $cfg.endpoint }}
  Endpoint     = {{$cfg.endpoint}}:{{$n.listen_port}}
  {{- end }}
  PublicKey    = {{$cfg.public_key}}
  PresharedKey = {{$n.preshared_key}}
  AllowedIPs   = {{$n.slash16}}.{{$cfg.machine_id}}.0/24
  {{- end }}
  {{- end }}
'''
[[symlink]]
path   = "/usr/share/holo/files/20-overlay-network/usr/lib/systemd/network/wg-overlay.netdev.holoscript"
target = "/usr/bin/replicator"

[[file]]
path    = "/usr/lib/systemd/network/wg-overlay.network"
content = '''
  [Match]
  Name = wg-overlay

  [Network]
  Address = {{.Vars.network.overlay.slash16}}.{{.Vars.host.id}}.1/16
'''
[[symlink]]
path   = "/usr/share/holo/files/20-overlay-network/usr/lib/systemd/network/wg-overlay.network.holoscript"
target = "/usr/bin/replicator"

################################################################################
# open ports for WireGuard when using hologram-ferm

[[file]]
path    = "/etc/ferm.d/incoming-overlay-network"
content = '''
  proto udp dport {{.Vars.network.overlay.listen_port}} ACCEPT;
'''
[[symlink]]
path   = "/usr/share/holo/files/20-network-overlay/etc/ferm.d/incoming-overlay-network.holoscript"
target = "/usr/bin/replicator"
