[package]
name        = "hologram-hyperv-guest"
version     = "0.0.1"
description = "hologram: Kernel modules, bootloader, network setup for Hyper-V VMs"

provides  = [ "hologram-vm-guest" ]
conflicts = [ "hologram-vmware-guest", "hologram-virtualbox-guest" ]

requires = [
    "hologram-base", # for systemd-networkd
    "hyperv",
    "xf86-input-libinput",
    "xf86-video-fbdev",
]

# NOTE TO SELF: According to <https://wiki.archlinux.org/index.php/Hyper-V>,
# the following steps must be executed in PowerShell to set up the network
# adapter:
#
# > New-VMSwitch -Name "VM-Internal-Switch" -SwitchType Internal
# > Get-NetAdapter # find interface index for vEthernet connected to this switch
# > New-NetIPAddress -IPAddress 192.168.3.1 -PrefixLength 24 -InterfaceIndex $INDEX
# > New-NetNat -Name "VM-NAT-Network" -InternalIPInterfaceAddressPrefix 192.168.3.1/24
#
# Then the VM can be connected to the vswitch thus created.

################################################################################
# hyperv tools

[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/hv_fcopy_daemon.service"
target = "/usr/lib/systemd/system/hv_fcopy_daemon.service"
[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/hv_kvp_daemon.service"
target = "/usr/lib/systemd/system/hv_kvp_daemon.service"
[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/hv_vss_daemon.service"
target = "/usr/lib/systemd/system/hv_vss_daemon.service"

################################################################################
# network setup (the DNS server is usually overridden by the machine's holodeck)

[[file]]
path    = "/etc/systemd/network/dhcp.network"
content = """
    [Match]
    Name=en*

    [Network]
    Description=Hyper-V Virtual Ethernet
    Address=192.168.3.2/24
    Gateway=192.168.3.1
    DNS=8.8.8.8
"""

# use systemd-resolved
[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/systemd-resolved.service"
target = "/usr/lib/systemd/system/systemd-resolved.service"

[[symlink]]
path   = "/usr/share/holo/files/20-hyperv/etc/resolv.conf"
target = "/run/systemd/resolve/resolv.conf"

################################################################################
# misc

[[file]]
path    = "/etc/modprobe.d/nobeep.conf"
content = "blacklist pcspkr"
