[package]
name        = "hologram-bethselamin-prosody"
version     = "1.1.1"
description = "hologram: Prosody on Bethselamin"

requires = [
    "prosody",
    "lua51-sec",  # TLS encryption support
    "lua51-zlib", # compression support
]

# open port when using hologram-ferm
[[file]]
path = "/etc/ferm.d/incoming-xmpp"
content = '''
    proto tcp dport xmpp-client ACCEPT;
    proto tcp dport xmpp-server ACCEPT;
'''

[[file]]
path    = "/usr/share/holo/files/50-bethselamin/etc/prosody/prosody.cfg.lua"
content = '''
    daemonize = true;
    pidfile   = "/run/prosody/prosody.pid";
    log       = { "*syslog"; };

    c2s_require_encryption = true;
    s2s_require_encryption = true;
    s2s_secure_auth        = false; -- TODO: not all remotes are correctly signed
    authentication = "internal_hashed";

    admins = { "stefan@bethselamin.de" };

    modules_disabled = {};
    modules_enabled  = {
        -- POSIX functionality (needs to be first to get the rest of the startup in syslog)
        "posix";
        -- user-facing features
        "roster"; "private"; "vcard";
        -- all the crypto
        "saslauth"; "tls";
        -- s2s dialback support
        "dialback";
        -- service discovery
        "disco";
        -- registration is disabled, but this allows users to change their password
        "register";
        -- this is apparently needed for Conversations to work
        "ping";
    };
    allow_registration = false;

    VirtualHost "bethselamin.de"
        ssl = {
            key = "/etc/prosody/certs/bethselamin.de.key";
            certificate = "/etc/prosody/certs/bethselamin.de.crt";
        };

'''

[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/prosody.service"
target = "/usr/lib/systemd/system/prosody.service"

[[file]]
path    = "/etc/letsencrypt-allofthem/prosody.sh"
mode    = "0755"
content = '''
    #!/bin/sh
    grep -o '/etc/letsencrypt/live/[^/]\+' /etc/letsencrypt-allofthem/then/prosody.sh | cut -d/ -f5 | sort -u
'''

[[file]]
path    = "/etc/letsencrypt-allofthem/then/prosody.sh"
mode    = "0755"
content = '''
    #!/bin/sh
    cp /etc/letsencrypt/live/bethselamin.de/privkey.pem /etc/prosody/certs/bethselamin.de.key
    cp /etc/letsencrypt/live/bethselamin.de/fullchain.pem /etc/prosody/certs/bethselamin.de.crt
    chown prosody:prosody /etc/prosody/certs/*
    chmod 0400 /etc/prosody/certs/*
'''
