[package]
name        = "hologram-dev-tools-minimal"
version     = "1.2.0"
description = "hologram: compilers and development tools (variant for space-constrained systems)"

requires = [
    "art",
    "base-devel",
    "cloc",
    "cpanminus",
    "go",
    "go-tools",
    "holo-build",
    "pacman-contrib", # updpkgsums
    "perl-data-dump",
    "perl-term-readkey", # required for "interactive.singlekey" config of Git
]
