[package]
name        = "hologram-dtp"
version     = "1.0.3"
description = "hologram: desktop publishing applications"

requires = [
    "texlive-plainextra",
    "texlive-latexextra",
    "texlive-pictures",
    "texlive-science",
]
