[package]
name        = "hologram-archlinux-mirror"
version     = "1.0.2"
description = "hologram: Arch Linux package mirror"

requires = [ "hologram-nginx" ]

################################################################################
# repo sync via cronjob

[[group]]
name   = "mirror"
system = true

[[user]]
name   = "mirror"
group  = "mirror"
home   = "/data/archlinux-mirror"
system = true

[[directory]]
path  = "/data/archlinux-mirror"
owner = "mirror"
group = "mirror"

[[directory]]
path  = "/data/archlinux-mirror/repo"
owner = "mirror"
group = "mirror"

[[directory]]
path  = "/data/archlinux-mirror/tmp"
owner = "mirror"
group = "mirror"

[[file]]
path = "/data/archlinux-mirror/repo/.autoindex"
contentFrom = "/dev/null"

[[file]]
path = "/usr/lib/archlinux-mirror/sync-repo.sh"
mode = "0755"
# originally from https://git.server-speed.net/users/flo/bin/plain/syncrepo.sh
contentFrom = "src/sync-repo.sh"

[[file]]
path    = "/usr/lib/systemd/system/archlinux-mirror-sync.service"
content = '''
    [Unit]
    Description=Sync Arch Linux package repo

    [Service]
    Type=oneshot
    ExecStart=/usr/lib/archlinux-mirror/sync-repo.sh
    User=mirror
    Group=mirror
'''

[[file]]
path    = "/usr/lib/systemd/system/archlinux-mirror-sync.timer"
content = '''
    [Unit]
    Description=Sync Arch Linux package repo every quarter-hour

    [Timer]
    OnBootSec=120
    OnUnitInactiveSec=900

    [Install]
    WantedBy=timers.target
'''

[[symlink]]
path   = "/etc/systemd/system/timers.target.wants/archlinux-mirror-sync.timer"
target = "/usr/lib/systemd/system/archlinux-mirror-sync.timer"

################################################################################
# repo publish via hologram-nginx's staticweb functionality

[[symlink]]
path   = "/data/static-web/mirror.bethselamin.de"
target = "/data/archlinux-mirror/repo"
