[package]
name        = "hologram-overlay-network-client"
version     = "0.0.3"
description = "hologram: client for private overlay network"

requires = [
  'secrets',       # this uses /usr/bin/replicator
  'linux-headers', # for DKMS
  'wireguard-dkms',
  'wireguard-tools',
]

################################################################################
# one WireGuard device per server

[[file]]
path    = "/usr/lib/systemd/network/wg-overlay-1.netdev"
mode    = "0640" # this file contains private keys
owner   = "root"
group   = "systemd-network"
content = "1"
[[symlink]]
path   = "/usr/share/holo/files/20-overlay-network/usr/lib/systemd/network/wg-overlay-1.netdev.holoscript"
target = "/usr/share/system-configuration/wg-overlay.netdev.holoscript"

[[file]]
path    = "/usr/lib/systemd/network/wg-overlay-2.netdev"
mode    = "0640" # this file contains private keys
owner   = "root"
group   = "systemd-network"
content = "2"
[[symlink]]
path   = "/usr/share/holo/files/20-overlay-network/usr/lib/systemd/network/wg-overlay-2.netdev.holoscript"
target = "/usr/share/system-configuration/wg-overlay.netdev.holoscript"

[[file]]
path    = "/usr/share/system-configuration/wg-overlay.netdev.template"
content = '''
  {{- $n := .Vars.network.overlay }}
  [NetDev]
  Name = wg-overlay-%SERVER_ID%
  Kind = wireguard
  Description = Overlay network

  [WireGuard]
  PrivateKey = {{$n.private_key}}

  {{- range $hostname, $cfg := $n.servers }}
  {{- if eq $cfg.server_id %SERVER_ID% }}
  [WireGuardPeer]
  Endpoint     = {{$cfg.endpoint}}:{{$n.listen_port}}
  PublicKey    = {{$cfg.public_key}}
  PresharedKey = {{$n.preshared_key}}
  AllowedIPs   = {{$n.slash16}}.0.0/16
  {{- end }}
  {{- end }}
'''

[[file]]
path    = "/usr/share/system-configuration/wg-overlay.netdev.holoscript"
mode    = "0755"
content = '''
  #!/bin/sh
  read SERVER_ID
  sed s/'%SERVER_ID%'/"${SERVER_ID}"/g < /usr/share/system-configuration/wg-overlay.netdev.template | replicator
'''

################################################################################
# network configuration for those devices

[[file]]
path    = "/usr/lib/systemd/network/wg-overlay.network"
content = '''
  [Match]
  Name = wg-overlay-*

  [Network]
  Address = {{.Vars.network.overlay.slash16}}.{{.Vars.host.id}}.1/16
'''
[[symlink]]
path   = "/usr/share/holo/files/20-overlay-network/usr/lib/systemd/network/wg-overlay.network.holoscript"
target = "/usr/bin/replicator"

# TODO: cannot set same address on all wg-overlay-* interfaces; use IPForward=yes?
# TODO: if so, use ferm everywhere and restrict forwarding to wg-overlay-*
