[package]
name        = "hologram-jack"
version     = "0.1.1"
description = "hologram: JACK audio server in addition to PulseAudio"

requires = [
  "cadence",
  "jack2-dbus",
  "lib32-jack2",
  "pulseaudio-jack",
  "realtime-privileges",
]

[[user]]
name   = "stefan"
groups = [ "realtime" ]

# In Cadence:
# - Set the ALSA briding mode to "ALSA -> PulseAudio -> JACK".
# - Configure the correct ALSA device with 2 input and output channels, each.
