[package]
name        = "hologram-kde-desktop-minimal"
version     = "1.1.3"
description = "hologram: GUI installation with KDE Plasma desktop (variant for space-constrained systems)"

requires = [
    "hologram-base-gui-minimal",
    # display manager
    "sddm",
    # desktop
    "group:plasma", "except:bluedevil", "except:plasma-nm", "except:ksshaskpass", "except:powerdevil", "except:plasma-vault",
    "except:breeze-gtk", # hilariously broken with GTK 3.20 ATM
    "gst-plugins-good",  # optional: for WebM support in qt5-webkit
    # KDE 5 applications
    "filelight",
    "kcharselect",
    "kcolorchooser",
    "kolourpaint",
    "konsole",
    "kruler",
    "spectacle",
    "yakuake",
    # platform integration for non-KDE desktop
    "qt5ct",
]

[[file]]
path    = "/etc/sddm.conf.d/20-kde-desktop.conf"
content = """
    [Autologin]
    User=stefan
    Session=plasma.desktop

    [Theme]
    Current=breeze
"""

[[symlink]]
path   = "/etc/systemd/system/display-manager.service"
target = "/usr/lib/systemd/system/sddm.service"
