[package]
name    = "hologram-no-sudo"
version = "1.0.1"
description = "hologram: block installation of sudo (despite it being a dependency in base-devel)"

provides = [ "a-decision-regarding-sudo", "sudo" ]
conflicts = [ "sudo" ]
