[package]
name        = "holodeck-traal"
version     = "20190208.1"
description = "holodeck: services on Traal"

requires = [
    "hologram-kde-desktop",
    "hologram-monitoring-client",
    "hologram-dev-tools",
    "hologram-games",
    "hologram-dtp",
    "hologram-uefi-bootloader-with-luks",
    "hologram-consul",
    "linux-headers", # for wireguard-dkms
    # basic hardware support
    "hologram-amd-ucode",
    "wpa_supplicant",
    "xf86-input-synaptics",
    # power management
    "tlp",
    "x86_energy_perf_policy", # optional dependency for tlp
    # support for AMD GPU
    "xf86-video-amdgpu",
    "vulkan-radeon",
    "lib32-vulkan-radeon",
    "vulkan-icd-loader",
    "lib32-vulkan-icd-loader",
    "mesa-libgl",
    "lib32-mesa-libgl",
    "mesa-vdpau",
    "lib32-mesa-vdpau",
    "libva-mesa-driver",
    "lib32-libva-mesa-driver",
    # applications
    "kdeconnect",
    "libreoffice-still",
    "mpd",
    "powerdevil",    # skipped in hologram-kde-desktop
    # offline docs (for travel)
    "rfc",
    "rust-docs",
    # trial runs
    "mutt",
]

# identity
[[file]]
path    = "/etc/hostname"
content = "traal"

[[file]]
path    = "/etc/profile.d/prettyprompt.sh"
content = """
export PRETTYPROMPT_COMMONUSER=stefan
export PRETTYPROMPT_HOSTCOLOR='0;34'
"""

# AMD APU requires iommu=soft kernel parameter to boot
[[file]]
path    = "/usr/share/holo/files/50-traal/boot/loader/entries/arch.conf.holoscript"
mode    = "0755"
content = '''
    #!/bin/sh
    sed '/options/s/$/ amd_iommu=pt ivrs_ioapic[32]=00:14.0/'
'''

# load AMDGPU driver during early boot
[[file]]
path    = "/usr/share/holo/files/50-traal/etc/mkinitcpio.conf.holoscript"
mode    = "0755"
content = """
    #!/bin/bash
    sed 's/^MODULES=.*$/MODULES=(amdgpu sdhci sdhci_pci)/'
"""

# make SD card slot work
[[file]]
path    = "/etc/modprobe.d/sdhci.conf"
content = 'options sdhci debug_quirks2="0x8000"'

# English keyboard layout
[[file]]
path    = "/usr/share/holo/files/50-traal/etc/vconsole.conf.holoscript"
mode    = "0755"
content = '''
    #!/bin/sh
    sed 's/KEYMAP=.*/KEYMAP=us/'
'''

[[file]]
path    = "/usr/share/holo/files/50-traal/etc/X11/xorg.conf.d/keyboard.conf.holoscript"
mode    = "0755"
content = """
    #!/bin/sh
    sed '/XkbLayout/s/de/en/;/XkbVariant/s/nodeadkeys/altgr-intl/'
"""

[[file]]
path    = "/usr/share/holo/files/50-traal/etc/profile.d/xkb.sh.holoscript"
mode    = "0755"
content = """
    #!/bin/sh
    sed '/LAYOUT/s/de/en/;/VARIANT/s/nodeadkeys/altgr-intl/'
"""

# Xorg: enable palm detection on touchpad, enable tapping, disable coasting
[[file]]
path    = "/etc/X11/xorg.conf.d/52-palm-detection.conf"
content = """
Section "InputClass"
    Identifier "touchpad enable palm detection"
    Driver "synaptics"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    Option "CoastingSpeed" "0"
    Option "PalmDetect" "on"
    Option "PalmMinWidth" "4"
    Option "PalmMinZ" "1"
    Option "TapButton1" "1"
    Option "TapButton2" "2"
    Option "TapButton3" "3"
EndSection
"""

# network setup: systemd-networkd
[[file]]
path    = "/etc/systemd/network/dhcp.network"
content = """
    [Match]
    Name=wl* en*

    [Network]
    Description=Use DHCP on physical interfaces
    DHCP=yes

    [DHCP]
    UseDomains=true
"""

# network setup: systemd-resolved
[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/systemd-resolved.service"
target = "/usr/lib/systemd/system/systemd-resolved.service"

[[symlink]]
path   = "/usr/share/holo/files/50-krikkit/etc/resolv.conf"
target = "/run/systemd/resolve/resolv.conf"

# network setup: wpa_supplicant
[[file]]
path = "/etc/wpa_supplicant/wpa_supplicant-wlp4s0.conf"
contentFrom = "/dev/null"
[[file]]
path    = "/usr/share/holo/files/50-krikkit/etc/wpa_supplicant/wpa_supplicant-wlp4s0.conf.holoscript"
mode    = "0755"
content = '''
    #!/bin/sh
    cat /home/stefan/.wpa_supplicant.conf
    cat /etc/wpa_supplicant/wpa_supplicant.conf
'''

[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/wpa_supplicant@wlp4s0.service"
target = "/usr/lib/systemd/system/wpa_supplicant@.service"

# no magic suspend
[[file]]
path = "/etc/systemd/logind.conf.d/no-magic-suspend.conf"
content = """
[Login]
HandleLidSwitch=ignore
"""

# enable TLP (laptop power-saving daemon)
[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/tlp.service"
target = "/usr/lib/systemd/system/tlp.service"
[[symlink]]
path   = "/etc/systemd/system/sleep.target.wants/tlp-sleep.service"
target = "/usr/lib/systemd/system/tlp-sleep.service"

[[symlink]]
path   = "/etc/systemd/system/NetworkManager.service"
target = "/dev/null"
[[symlink]]
path   = "/etc/systemd/system/systemd-rfkill.service"
target = "/dev/null"
[[symlink]]
path   = "/etc/systemd/system/systemd-rfkill.socket"
target = "/dev/null"
