[package]
name        = "hologram-multimedia-base"
version     = "1.0.12"
description = "hologram: basic multimedia software collection (no GUI required)"

requires = [
    "pipewire",
    "pipewire-alsa",
    "pipewire-jack",
    "pipewire-pulse",
    "lib32-pipewire-jack",
    # clients
    "mpc",
    "mpv",
    "mpv-mpris",
    "ncmpcpp",
    # tools
    "mp3splt", # contains oggsplt
    "opus-tools",
    "pamixer",   # used by my Sway keybindings for XF86Audio{Mute,{Lower,Raise}Volume}
    "playerctl", # CLI for MPRIS
    "vorbis-tools",
    "vorbisgain",
    "yt-dlp",
    "rtmpdump", # optional for youtube-dl
]

[[file]]
path = "/etc/mpv/mpv.conf"
content = '''
    # never display album covers
    no-audio-display
    # always start fullscreen by default
    fs
    # enumerate unfinished videos by examining the watch-later files
    write-filename-in-watch-later-config
'''
