[package]
name        = "hologram-vmware-guest"
version     = "0.0.3"
description = "hologram: Kernel modules, bootloader, network setup for VMware VMs"

requires = [
    "hologram-base", # for systemd-networkd
    "hologram-uefi-bootloader",
    "open-vm-tools",
    "xf86-input-vmmouse",
    "xf86-video-vmware",
]

# NOTE TO SELF: For UEFI to work, open up the .vmx file defining the VM in a
# text editor and add the line:
#
#   firmware = "efi"
#
# Furthermore, this hologram assumes that the virtual ethernet device is set up
# as NAT.

################################################################################
# open-vm-tools

[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/vmtoolsd.service"
target = "/usr/lib/systemd/system/vmtoolsd.service"
[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/vmware-vmblock-fuse.service"
target = "/usr/lib/systemd/system/vmware-vmblock-fuse.service"

################################################################################
# network setup

[[file]]
path    = "/etc/systemd/network/dhcp.network"
content = """
    [Match]
    Name=en*

    [Network]
    Description=DHCP to host
    DHCP=yes

    [DHCP]
    UseDomains=true
"""

# use systemd-resolved
[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/systemd-resolved.service"
target = "/usr/lib/systemd/system/systemd-resolved.service"

[[symlink]]
path   = "/usr/share/holo/files/20-vmware/etc/resolv.conf"
target = "/run/systemd/resolve/resolv.conf"

################################################################################
# misc

[[file]]
path    = "/etc/modprobe.d/nobeep.conf"
content = "blacklist pcspkr"
