[package]
name        = "holodeck-work-lxc"
version     = "1.0.2"
description = "holodeck: base configuration for headless LXC containers"

requires = [
  "hologram-base-accessible",
  "hologram-dev-tools-minimal",
  "hologram-nix-daemon",
  # assorted tools
  "docker",
  "ipython",
  "pgcli",
  "postgresql",
  "python-pip",
  "python-virtualenv",
  "rfc",
  "sshuttle",
  "trivy",
  "vault",
]

[[user]]
name   = "stefan"
groups = ["docker"]

[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/docker.service"
target = "/usr/lib/systemd/system/docker.service"
