#!/bin/bash

if [ $# -ne 1 ]; then
    exec >&2
    echo "Usage: $0 <hostname>"
    echo "Connects to the given host and displays its Munin statistics webpage."
    exit 1
fi

HOSTNAME="$1"
MOUNTPOINT="$XDG_RUNTIME_DIR/munin/$HOSTNAME"

mkdir -p "${MOUNTPOINT}"
if [ ! -f "${MOUNTPOINT}/index.html" ]; then
    sshfs "${HOSTNAME}:/data/munin/html" "${MOUNTPOINT}"
fi

xdg-open "${MOUNTPOINT}/${HOSTNAME}/${HOSTNAME}/index.html"
