global:
  scrape_interval:     60s
  evaluation_interval: 60s
  scrape_timeout:      5s

rule_files: []

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:{{.Vars.prometheus.http_port}}']

  - job_name: consul
    consul_sd_configs:
      - server: 127.0.0.1:8500
    relabel_configs:
      - source_labels: [__meta_consul_node]
        target_label: instance
      - source_labels: [__meta_consul_service]
        target_label: job
