global:
  scrape_interval:     60s
  evaluation_interval: 60s

rule_files: []

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:{{.Vars.prometheus.http_port}}']
